"""customerDelivery table

Revision ID: 02efddf85d02
Revises: 3fd37f13fce9
Create Date: 2018-05-13 00:01:44.129082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02efddf85d02'
down_revision = '3fd37f13fce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerDelivery',
    sa.Column('Delivery', sa.Integer(), nullable=False),
    sa.Column('Customer', sa.Integer(), nullable=False),
    sa.Column('Order Date', sa.DateTime(), nullable=True),
    sa.Column('Expected Delivery Date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Customer'], ['customer.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Delivery'], ['delivery.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Delivery', 'Customer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customerDelivery')
    # ### end Alembic commands ###
