"""delivery table

Revision ID: 3fd37f13fce9
Revises: f0f8578c6dec
Create Date: 2018-05-13 00:00:49.162778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd37f13fce9'
down_revision = 'f0f8578c6dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Address', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_Address'), 'delivery', ['Address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_Address'), table_name='delivery')
    op.drop_table('delivery')
    # ### end Alembic commands ###
