"""empty message

Revision ID: 43f1518cdbd7
Revises: 56e4bc0a9967
Create Date: 2018-05-25 22:27:52.347642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f1518cdbd7'
down_revision = '56e4bc0a9967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pan', sa.Column('Rail Height', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pan', 'Rail Height')
    # ### end Alembic commands ###
