"""content table

Revision ID: 4d29f16f74c7
Revises: 02efddf85d02
Create Date: 2018-05-13 00:03:01.836841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d29f16f74c7'
down_revision = '02efddf85d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_expiry_date'), 'content', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_content_name'), 'content', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_name'), table_name='content')
    op.drop_index(op.f('ix_content_expiry_date'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
