"""delivery table

Revision ID: 56e4bc0a9967
Revises: 15421191625d
Create Date: 2018-05-17 13:58:11.512870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e4bc0a9967'
down_revision = '15421191625d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('Pan ID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery', 'pan', ['Pan ID'], ['id'], onupdate='Cascade', ondelete='SET NULL')
    op.add_column('pallet', sa.Column('Delivery ID', sa.Integer(), nullable=False))
    op.drop_constraint('pallet_Pan ID_fkey', 'pallet', type_='foreignkey')
    op.create_foreign_key(None, 'pallet', 'delivery', ['Delivery ID'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('pallet', 'Pan ID')
    op.drop_constraint('pan_Delivery ID_fkey', 'pan', type_='foreignkey')
    op.drop_column('pan', 'Delivery ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pan', sa.Column('Delivery ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pan_Delivery ID_fkey', 'pan', 'delivery', ['Delivery ID'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('pallet', sa.Column('Pan ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pallet', type_='foreignkey')
    op.create_foreign_key('pallet_Pan ID_fkey', 'pallet', 'pan', ['Pan ID'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('pallet', 'Delivery ID')
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'Pan ID')
    # ### end Alembic commands ###
