"""pancoordinator table

Revision ID: acc202c34e9e
Revises: 56e4bc0a9967
Create Date: 2018-05-29 15:20:56.918809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc202c34e9e'
down_revision = '43f1518cdbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pan_coordinator',
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('Width Position', sa.Integer(), nullable=False),
    sa.Column('Length Position', sa.Integer(), nullable=False),
    sa.Column('Height Position', sa.Integer(), nullable=False),
    sa.Column('Rail', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallet.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pallet_id')
    )
    op.add_column('palletContent', sa.Column('content_id', sa.Integer(), nullable=False))
    op.add_column('palletContent', sa.Column('content_type', sa.String(length=64), nullable=True))
    op.add_column('palletContent', sa.Column('pallet_id', sa.Integer(), nullable=False))
    op.add_column('palletContent', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_palletContent_content_type'), 'palletContent', ['content_type'], unique=False)
    op.drop_index('ix_palletContent_Content Type', table_name='palletContent')
    op.drop_constraint('palletContent_Content ID_fkey', 'palletContent', type_='foreignkey')
    op.drop_constraint('palletContent_Pallet ID_fkey', 'palletContent', type_='foreignkey')
    op.create_foreign_key(None, 'palletContent', 'pallet', ['pallet_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'palletContent', 'content', ['content_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('palletContent', 'Content ID')
    op.drop_column('palletContent', 'Pallet ID')
    op.drop_column('palletContent', 'Content Type')
    op.drop_column('palletContent', 'Quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pan', 'Rail Height')
    op.add_column('palletContent', sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('palletContent', sa.Column('Content Type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('palletContent', sa.Column('Pallet ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('palletContent', sa.Column('Content ID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'palletContent', type_='foreignkey')
    op.drop_constraint(None, 'palletContent', type_='foreignkey')
    op.create_foreign_key('palletContent_Pallet ID_fkey', 'palletContent', 'pallet', ['Pallet ID'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('palletContent_Content ID_fkey', 'palletContent', 'content', ['Content ID'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_palletContent_Content Type', 'palletContent', ['Content Type'], unique=False)
    op.drop_index(op.f('ix_palletContent_content_type'), table_name='palletContent')
    op.drop_column('palletContent', 'quantity')
    op.drop_column('palletContent', 'pallet_id')
    op.drop_column('palletContent', 'content_type')
    op.drop_column('palletContent', 'content_id')
    op.drop_table('pan_coordinator')
    # ### end Alembic commands ###
