"""Increasing phone number length

Revision ID: d8acf625b8e9
Revises: 561e1d3d0a47
Create Date: 2018-06-04 14:51:24.403416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8acf625b8e9'
down_revision = '561e1d3d0a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'Phone Number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'Phone Number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
