"""pallet table

Revision ID: e188498408d1
Revises: a8a82ccb28e7
Create Date: 2018-05-13 00:07:39.184109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e188498408d1'
down_revision = 'a8a82ccb28e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Weight', sa.Numeric(), nullable=False),
    sa.Column('Height', sa.Numeric(), nullable=False),
    sa.Column('Category', sa.String(length=1), nullable=False),
    sa.Column('Can Stack', sa.Boolean(), nullable=False),
    sa.Column('Customer ID', sa.Integer(), nullable=False),
    sa.Column('Pan ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Customer ID'], ['customer.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Pan ID'], ['pan.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pallet')
    # ### end Alembic commands ###
