"""customer table

Revision ID: f0f8578c6dec
Revises: 0cd6fe387123
Create Date: 2018-05-12 23:56:39.157338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f8578c6dec'
down_revision = '0cd6fe387123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First Name', sa.String(length=64), nullable=False),
    sa.Column('Last Name', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Address', sa.String(length=128), nullable=True),
    sa.Column('Phone Number', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Phone Number')
    )
    op.create_index(op.f('ix_customer_First Name'), 'customer', ['First Name'], unique=False)
    op.create_index(op.f('ix_customer_Last Name'), 'customer', ['Last Name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_Last Name'), table_name='customer')
    op.drop_index(op.f('ix_customer_First Name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
